# Generated by Django 6.1 on 2026-08-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
