# Generated by Django 6.1 on 2026-08-16 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_academicyear_id_alter_course_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('notice_type', models.CharField(choices=[('GENERAL', 'General'), ('ACADEMIC', 'Academic'), ('EXAM', 'Examination'), ('FEE', 'Fee & Payment'), ('HOLIDAY', 'Holiday'), ('EVENT', 'Event / Function'), ('EMERGENCY', 'Emergency Alert'), ('ASSIGNMENT', 'Assignment Notice'), ('ATTENDANCE', 'Attendance Alert'), ('RESULT', 'Result Announcement')], default='GENERAL', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent / Critical')], default='NORMAL', max_length=20)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('target_audience', models.CharField(choices=[('EVERYONE', 'Everyone'), ('STUDENTS', 'Students Only'), ('FACULTY', 'Faculty Only'), ('DEPARTMENT', 'Specific Department'), ('COURSE', 'Specific Course'), ('SEMESTER', 'Specific Semester')], default='EVERYONE', max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='academics.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='academics.department')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='academics.semester')),
            ],
            options={
                'ordering': ['-priority', '-publish_date', '-created_at'],
            },
        ),
    ]
