# Generated by Django 6.1 on 2026-08-16 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('CERTIFICATE', 'Academic Certificate'), ('MARK_SHEET', 'Mark Sheet / Transcript'), ('IDENTITY', 'Identity Proof (ID/Aadhaar)'), ('ADMISSION', 'Admission Form / Letter'), ('RESEARCH', 'Research Paper / Project Report'), ('OTHER', 'Other Document')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
