# Generated by Django 6.1 on 2026-08-16 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_academicyear_id_alter_course_id_and_more'),
        ('faculty', '0003_alter_faculty_id_facultysubjectassignment'),
        ('students', '0003_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='faculty.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academics.subject')),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/')),
                ('submission_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('GRADED', 'Graded'), ('RETURNED', 'Returned')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_student_submission')],
            },
        ),
    ]
