# Generated by Django 6.1 on 2026-08-16 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_academicyear_id_alter_course_id_and_more'),
        ('faculty', '0003_alter_faculty_id_facultysubjectassignment'),
        ('results', '0002_alter_exam_options_exam_description_exam_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='academics.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='academics.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='results.exam')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilation_schedules', to='faculty.faculty', verbose_name='Invigilator')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='academics.subject')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'subject', 'course', 'semester', 'exam_date'), name='unique_exam_schedule')],
            },
        ),
    ]
